### ISSUE TITLE
[Task] <access tokens management feature>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1002]
### Description

support manage hertzbeat access tokens in web ui 

### Task List

- [ ] support generate new access token
- [ ] support delete access token
- [ ] unit test and document

**Comment by tomsun28** [comment]
> Hi,do you mean the JWT token authentication?

yes, we have support jwt. this feature is to manage jwt in web.

**Comment by l646505418** [comment]
I can work on this , can assign to me

**Comment by l646505418** [comment]
Hi @tomsun28 ,我看代码好像request的header只有JWT token，但是token过期的时候，连userId都解析不出来，这样就无法在db里面删除过期的token数据。我的想法是在后端重新创建一个token pojo，给它分配一个id，前端传token的时候也可以把id传过来以便做数据库的增上改查，不知道这样是否可行？

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hi @tomsun28, I see the code as if the header of the request only has the JWT token, but when the token expires, even the userId cannot be parsed out, so the expired token data cannot be deleted in the db. My idea is to recreate a token pojo on the backend and assign it an id. When the token is passed on the front end, the id can also be passed over for the purpose of adding, modifying and checking the database. I wonder if this is feasible?

**Comment by tomsun28** [comment]
> Hi @tomsun28 ,我看代码好像request的header只有JWT token，但是token过期的时候，连userId都解析不出来，这样就无法在db里面删除过期的token数据。我的想法是在后端重新创建一个token pojo，给它分配一个id，前端传token的时候也可以把id传过来以便做数据库的增上改查，不知道这样是否可行？

hi 你的意思认证的时候需要传一个token和id吗，这样就不能符合openapi认证token规范了。你看这样行不行，可以设计一张已签发token的数据表，里面有字段 token，签发时间和过期时间等。用户签发token的删除应该是用户手动删除了，即使token过期的情况下，可以参考下GitHub Gitee 的token管理api。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Hi @tomsun28, I see the code as if the header of the request only has the JWT token, but when the token expires, even the userId cannot be parsed, so the expired token data cannot be deleted in the db. My idea is to recreate a token pojo on the backend and assign it an id. When the token is passed on the front end, the id can also be passed over for the purpose of adding, modifying and checking the database. I wonder if this is feasible?

Hi, do you mean that a token and id need to be passed during authentication, so that it cannot comply with the openapi authentication token specification. You can see if this works, you can design a data table of issued tokens, which contains fields token, issuance time and expiration time, etc. The deletion of the token issued by the user should be manually deleted by the user. Even if the token expires, you can refer to the token management api of GitHub Gitee.

**Comment by l646505418** [comment]
> > Hi @tomsun28 ,我看代码好像request的header只有JWT token，但是token过期的时候，连userId都解析不出来，这样就无法在db里面删除过期的token数据。我的想法是在后端重新创建一个token pojo，给它分配一个id，前端传token的时候也可以把id传过来以便做数据库的增上改查，不知道这样是否可行？
> 
> hi 你的意思认证的时候需要传一个token和id吗，这样就不能符合openapi认证token规范了。你看这样行不行，可以设计一张已签发token的数据表，里面有字段 token，签发时间和过期时间等。用户签发token的删除应该是用户手动删除了，即使token过期的情况下，可以参考下GitHub Gitee 的token管理api。

意思是用户登陆所使用的token和用户调用generateToken所获得token区分开吗？我觉得可行，hhh
而且是不是可以限制用户签发token的数量以防他疯狂签发

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > Hi @tomsun28, I see the code as if the header of the request only has the JWT token, but when the token expires, even the userId cannot be parsed, so the expired token data cannot be deleted in the db. My idea is to re-create a token pojo on the backend and assign it an id. When the token is passed on the front end, the id can also be passed over for the purpose of adding, modifying and checking the database. I wonder if this is feasible?
>
> hi Do you mean that a token and id need to be passed during authentication, so that it cannot comply with the openapi authentication token specification. You can see if this works, you can design a data table of issued tokens, which contains fields token, issuance time and expiration time, etc. The deletion of the token issued by the user should be manually deleted by the user. Even if the token expires, you can refer to the token management api of GitHub Gitee.

Does it mean that the token used by the user to log in is different from the token obtained by the user calling generateToken? I think it works, hhh
And is it possible to limit the number of tokens issued by the user to prevent him from issuing them insanely?

**Comment by tomsun28** [comment]
> 意思是用户登陆所使用的token和用户调用generateToken所获得token区分开吗？我觉得可行，hhh 而且是不是可以限制用户签发token的数量以防他疯狂签发

是的，这两个可以是不同的API，因为用户生成的token可以设置过期时间等参数，我们可以提供一套api供用户自定义token的管理。感觉应该限制下生成数量，这样的话一个是更安全，而且我们也不用去做分页了，可以限制8个或者10个左右。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Does it mean that the token used by the user to log in is different from the token obtained by the user calling generateToken? I think it is feasible, hhh and is it possible to limit the number of tokens issued by the user to prevent him from issuing them insanely?

Yes, these two can be different APIs, because the token generated by the user can set parameters such as expiration time, we can provide a set of APIs for user-defined token management. I feel that the number of generated should be limited, so that one is safer, and we don't need to do paging, we can limit about 8 or 10.
