### ISSUE TITLE
[Task] <support for forwarding alarm messages from third-party platforms to hertzbeat>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1100]
### Description

Support for forwarding alarm messages from third-party platforms to hertzbeat. 

We use hertzbeat as an alarm center, access alarm information from other platforms, and then process alarm messages uniformly

![image](https://github.com/dromara/hertzbeat/assets/24788200/5e76562f-e159-4b6c-8540-f92d760f73a0)

### Task List

- [ ] support send aliyun alarm message by webhook
- [ ] support send huaweicloud alarm message by webhook
- [ ] support send tencent cloud alarm message by webhook

**Comment by zqr10159** [comment]
这个report接口暂时还没做？

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
This report interface has not been done yet?

**Comment by tomsun28** [comment]
> 这个report接口暂时还没做？

report api 有的，但是还没有对每个平台的适配接口，比如aliyun通过我们这边一个适配接口可以直接webhook数据进来

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> This report interface has not been done yet?

There are report apis, but there is no adaptation interface for each platform. For example, aliyun can directly enter webhook data through an adaptation interface on our side

**Comment by zqr10159** [comment]
ok看到接口了有空研究一下

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Ok, I saw the interface. I have time to study it.
