### ISSUE TITLE
[Task] Monitoring Template Yml Metrics I18n | 监控模版指标国际化任务认领 

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1212]
### Description

**Monitoring Template Yml Metrics I18n Task**  
> 监控模版指标国际化任务认领  

Hi guys, in the past, the `Metrics Name` of `HertzBeat` monitoring details could only display the English field, and could not support the configuration to display international name aliases such as English and Chinese. We are very glad that this version supports it. We have configured the internationalized name of the metrics into the monitoring template YML of each monitoring type. Because there are too many monitoring templates and the translation of the metrics name of each monitoring type needs to be considered, so I ask for your help here. Interested partners are welcome to cooperate and contribute to the internationalization of the monitoring template metrics translation. Thanks!

> 小伙伴们大家好，之前`HertzBeat`的监控详情的`指标名称`只能展示英文指标field字段，无法支持配置展示英文中文等国际化名称别名。很高兴这个版本我们对其支持了，指标的国际化名称我们将其配置到了各个监控类型的监控模版YML中。因为监控模版实在太多且每个监控类型的指标名称翻译都需要考量，所以在这里请求大家的帮助，欢迎感兴趣的小伙伴协作贡献大家一起把监控模版指标翻译国际化做好。谢谢，爱心💗！

Demo before:

<img width="1349" alt="image" src="https://github.com/dromara/hertzbeat/assets/24788200/46197c44-f184-43da-8ce6-6b17a2f0c16f">

After Metrics I18n:

<img width="1370" alt="image" src="https://github.com/dromara/hertzbeat/assets/24788200/8b89c63f-7e74-4b02-875d-d34eef28b2d4">

### Task List

Just comment on the corresponding task under this issue, and one PR corresponds to one monitoring template YML. as follows:   
> 领取方式，在本 issues 下评论对应任务即可，一个PR对应一个监控模版YML。如下:

- [x] Metrics I18n https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-zookeeper.yml

```
- [x] Metrics I18n https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-zookeeper.yml

```
Add i18n translation content under the metrics group and fields, for example: `i18n.zh-CN: CPU 信息 i18n.en-US: CPU Info`, English and Chinese are required, please pay attention to format alignment.

在指标组和指标下面添加i18n翻译内容, 例如：`i18n.zh-CN: CPU 信息 i18n.en-US: CPU Info`，需支持英文和中文，请注意格式对齐。  

Example: 
```
  - name: cpu
    i18n:
      zh-CN: CPU 信息
      en-US: CPU Info
    priority: 1
    fields:
      - field: info
        type: 1
        i18n:
          zh-CN: 型号
          en-US: Info
      - field: cores
        type: 0
        i18n:
          zh-CN: 核数
          en-US: Cores
      - field: interrupt
        type: 0
        i18n:
          zh-CN: 中断数
          en-US: Interrupt
      - field: load
        type: 1
        i18n:
          zh-CN: 负载
          en-US: Load
      - field: context_switch
        type: 0
        i18n:
          zh-CN: 上下文切换
          en-US: Context Switch
      - field: usage
        type: 0
        unit: '%'
        i18n:
          zh-CN: 使用率
          en-US: Usage
```

**Comment by jcmyt** [comment]
请问那个版本支持了啊 ，我现在使用的最新的1.40版本，还不支持，替换define目录下的yml文件，服务直接崩溃了。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
May I ask which version supports it? The latest 1.40 version I am using now does not support it. If the yml file in the define directory is replaced, the service directly crashes.

**Comment by tomsun28** [comment]
> 请问哪个版本支持了啊 ？我现在使用的最新的1.40安装版本（Windows），还不支持，替换define目录下的yml文件，服务直接崩溃了。 May I ask which version supports it? The latest 1.40 version I am using now does not support it. If the yml file in the define directory is replaced, the service directly crashes.

hi你好，国际化目前只能是在master分支代码本地启动支持，我们尽快发布支持新版本

**Comment by qyaaaa** [comment]
- [x] [ping] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-ping.yml)

**Comment by novohit** [comment]
[api] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-api.yml)

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
[api] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-api.yml)

**Comment by a-little-fool** [comment]
i want to help

**Comment by tomsun28** [comment]
> Just comment on the corresponding task under this issue, and one PR corresponds to one monitoring template YML

welcome. Just comment on the corresponding task under this issue, and one PR corresponds to one monitoring template YML.

**Comment by a-little-fool** [comment]
[mysql]（https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-mysql.yml）

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
[mysql]（https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-mysql.yml）

**Comment by a-little-fool** [comment]
[mysql]（https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-mysql.yml）

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
[mysql]（https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-mysql.yml）

**Comment by a-little-fool** [comment]
[jvm]（https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-jvm.yml）

**Comment by a-little-fool** [comment]
[mysql]（https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-mysql.yml）

**Comment by a-little-fool** [comment]
[mongodb] ( https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-mongodb.yml )

**Comment by idongliming** [comment]
[springboot2] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-springboot2.yml)

**Comment by a-little-fool** [comment]
[mongodb] ( https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-mongodb.yml )

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
[mongodb] ( https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-mongodb.yml )

**Comment by Calvin979** [comment]
- [x] [jvm] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-jvm.yml)
#1376

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
- [x] [jvm] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-jvm.yml)
#1376

**Comment by Calvin979** [comment]
- [x] [redis] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-redis.yml)
#1390

**Comment by ZY945** [comment]
[rabbitmq] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-rabbitmq.yml)

**Comment by liyin** [comment]
[springboot3] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-springboot3.yml)

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
[springboot3] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-springboot3.yml)

**Comment by liyin** [comment]
[docker] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-docker.yml)

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
[docker] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-docker.yml)

**Comment by tslj1024** [comment]
- [x] [docker] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-docker.yml)

**Comment by oyiyou** [comment]
[redis] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-redis.yml)

**Comment by cuipiheqiuqiu** [comment]
- [x] Metrics I18n [flink] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-flink.yml)

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
- [x] Metrics I18n [flink] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-flink.yml)

**Comment by cuipiheqiuqiu** [comment]
- [x] Metrics I18 [kubernetes] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-kubernetes.yml)

**Comment by cuipiheqiuqiu** [comment]
- [x] Metrics I18n [zookeeper] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-zookeeper.yml)

**Comment by ZY945** [comment]
[dynamic_tp] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-dynamic_tp.yml)

**Comment by ZY945** [comment]
[airflow] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-airflow.yml)

**Comment by ZY945** [comment]
[iotdb] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-iotdb.yml)

**Comment by ZY945** [comment]
[rocketmq] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-rocketmq.yml)

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
[rocketmq] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-rocketmq.yml)

**Comment by cuipiheqiuqiu** [comment]
Metrics I18n [kafka] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-kafka.yml)

**Comment by cuipiheqiuqiu** [comment]
[kafka_promql] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-kafka_promql.yml)

**Comment by zuobiao-zhou** [comment]
[dm] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-dm.yml)
[opengauss] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-opengauss.yml)
[sqlserver] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-sqlserver.yml)
BTW, 
[fullsite] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-fullsite.yml) , 
[nacos] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-nacos.yml) and 
[tomcat] (https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-tomcat.yml)
has been completed
