### ISSUE TITLE
[Task] 优化建议

### ISSUE THREAD

**Issue by gmij** [dromara/hertzbeat#1509]
### Description

新手使用过程中，碰到的一些问题，及自己的建议。请查收。感谢@tom 的支持。

### Task List

- [ ] 系统设置的位置，增加存储层配置。不要让用户去改配置文件
- [ ] 操作系统监控模板，把流量的显示，调整成按Mb显示，不要用Bytes显示
- [ ] Nginx的配置，只开启stub_status时应允许添加，当前报502错误。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Description

Some problems encountered by novices during use and their own suggestions. please check. Thanks @tom for your support.

### Task List

- [ ] The location of system settings, adding storage layer configuration. Don’t let users change configuration files
- [ ] Operating system monitoring template, adjust the display of traffic to display in Mb, do not display in Bytes
- [ ] Nginx configuration, it should be allowed to add when only stub_status is enabled. Currently, a 502 error is reported.

**Comment by tomsun28** [comment]
👍

**Comment by Calvin979** [comment]
I'd like to help

**Comment by tomsun28** [comment]
> I'd like to help

👍👍 welcome, we can consider this two points first.

-  操作系统监控模板，把流量的显示，调整成按Mb显示，不要用Bytes显示
-  Nginx的配置，只开启stub_status时应允许添加，当前报502错误。

**Comment by Calvin979** [comment]
- [ ] 操作系统监控模板中，网卡信息默认按MB显式
#1521

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
- [ ] In the operating system monitoring template, the network card information is displayed in MB by default.
#1521

**Comment by Calvin979** [comment]
@gmij hello，关于问题3。我这边没有复现出来，你可以试一下以下两种方式：
1、检查下Nginx的路由配置是否正确
2、删除Nginx的yml模板中关于req_status的监控配置
![image](https://github.com/dromara/hertzbeat/assets/131688897/80515963-2f3b-49a5-9093-311dc332a0b0)

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@gmij hello, regarding question 3. I haven't reproduced it here. You can try the following two methods:
1. Check whether the routing configuration of Nginx is correct.
2. Delete the monitoring configuration about req_status in the Nginx yml template.
![image](https://github.com/dromara/hertzbeat/assets/131688897/80515963-2f3b-49a5-9093-311dc332a0b0)

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@Calvin979
1. Confirm that the routing configuration of nginx is correct.
2. If req_status can be disabled by default, can it be commented out in the template and enabled by those who need it? Will this provide a better user experience?

**Comment by Calvin979** [comment]
@tomsun28 是否需要注释Nginx监控模板中req status的相关监控配置

**Comment by tomsun28** [comment]
hi，不启用 req_status 模块的情况下也是可以添加nginx监控的，建议如果用户不需要req_status的相关指标，可以自己去监控模版注释掉对应配置，我们默认还是保留吧。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hi, nginx monitoring can be added without enabling the req_status module. It is recommended that if the user does not need the relevant indicators of req_status, he can comment out the corresponding configuration in the monitoring template. We will keep it by default.
