### ISSUE TITLE
[Task] <Translate some hertzbeat chinese blogs to english in website >

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1567]
### Description

Translate some hertzbeat chinese blogs to english, suggest use google translate and gpt.   
Attention markdown style. 
Code Locaion: https://github.com/dromara/hertzbeat/tree/master/home/blog

### Task List

- [x] https://hertzbeat.com/blog/2024/01/11/new-committer
- [x] https://hertzbeat.com/blog/2023/08/28/new-committer
- [x] https://hertzbeat.com/blog/2023/05/11/greptimedb-store
- [x] https://hertzbeat.com/blog/2023/02/02/monitor-dynamic-tp
- [x] https://hertzbeat.com/blog/2023/01/08/monitor-shenyu
- [x] https://hertzbeat.com/blog/2022/12/19/new-committer
- [x] https://hertzbeat.com/blog/2022/10/08/hertzbeat-v1.2.0
- [x] https://hertzbeat.com/blog/2022/09/10/ssl-practice
- [ ] https://hertzbeat.com/blog/2022/09/04/hertzbeat-v1.1.3
- [ ] https://hertzbeat.com/blog/2022/06/22/one-step-up
- [ ] https://hertzbeat.com/blog/2022/06/19/hertzbeat-v1.1.0
- [ ] https://hertzbeat.com/blog/2022/06/01/hertzbeat-v1.0
- [ ] https://hertzbeat.com/blog/2022/05/17/hertzbeat-v1.0-beta.8
- [ ] https://hertzbeat.com/blog/2022/04/08/hertzbeat-v1.0-beta.7
- [ ] https://hertzbeat.com/blog/2022/03/20/hertzbeat-v1.0-beta.6
- [ ] https://hertzbeat.com/blog/2022/03/20/hertzbeat-v1.0-beta.5
- [ ] https://hertzbeat.com/blog/2022/02/28/hertzbeat-v1.0-beta.4
- [ ] https://hertzbeat.com/blog/2022/02/17/hertzbeat
- [ ] https://hertzbeat.com/blog/2022/02/11/hertzbeat

**Comment by zqr10159** [comment]
Which directory should I put the English documents under?

**Comment by tomsun28** [comment]
> https://github.com/dromara/hertzbeat/tree/master/home/blog

here, https://github.com/dromara/hertzbeat/tree/master/home/blog in `home/blog`, you can comment the task list you want to implement, like this. 

- [x] https://hertzbeat.com/blog/2024/01/11/new-committer
- [x] xxxx
- [x] xxxx

**Comment by zqr10159** [comment]
- [x] https://hertzbeat.com/blog/2024/01/11/new-committer

**Comment by zqr10159** [comment]
- [x] https://hertzbeat.com/blog/2023/08/28/new-committer
- [x] https://hertzbeat.com/blog/2023/05/11/greptimedb-store

**Comment by zqr10159** [comment]
- [x] https://hertzbeat.com/blog/2023/02/02/monitor-dynamic-tp
#1583

**Comment by a-little-fool** [comment]
[✅] https://hertzbeat.com/blog/2023/01/08/monitor-shenyu
 [✅] https://hertzbeat.com/blog/2022/12/19/new-committer
 [✅] https://hertzbeat.com/blog/2022/10/08/hertzbeat-v1.2.0
 [✅] https://hertzbeat.com/blog/2022/09/10/ssl-practice

**Comment by 5s5z5w5** [comment]
https://hertzbeat.com/blog/2023/01/08/monitor-shenyu/

**Comment by tomsun28** [comment]
> https://hertzbeat.com/blog/2023/01/08/monitor-shenyu/

hi, welcome. this one already been implemented by upstair, you can try other one.

**Comment by 666LarryEllison** [comment]
i want to help the https://hertzbeat.com/blog/2022/06/22/one-step-up

**Comment by TJxiaobao** [comment]
Does this directly cover the original article?

**Comment by wang1027-wqh** [comment]
https://hertzbeat.com/blog/2022/02/17/hertzbeat
 https://hertzbeat.com/blog/2022/02/11/hertzbeat

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
https://hertzbeat.com/blog/2022/02/17/hertzbeat
 https://hertzbeat.com/blog/2022/02/11/hertzbeat
