### ISSUE TITLE
[Task] <monitoring params support depende enable by other params>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1705]
### Description

monitoring params support depende enable by other params.
such as, we need params app-version, it has values: v1, v2, v3. Each version value(v1, v2, v3) will connect different parmas what we need input. eg: v1 map key2, v2 map key4 

### Task List

- [ ] design the monitoring template params structure. 
- [ ] monitoring params support depende enable by other params.
- [ ] test and apply in monitor tempalte - snmp.

**Comment by zuobiao-zhou** [comment]
I can help.

**Comment by tomsun28** [comment]
> I can help.

welcome👍
