### ISSUE TITLE
[Task] <support using `GaussDB For Influx` store history metrics data>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#836]
### Huawei Cloud & HertzBeat 's Feature Task 

support using `GaussDB For Influx` store history metrics data, like tdengine and iotdb. 
refer doc https://support.huaweicloud.com/influxug-nosql/nosql_09_0101.html
sdk https://github.com/influxdata/influxdb-java 

⚠️ InfluxDB Version Supported 1.7

### Task List

- [ ] support using `GaussDB For Influx` store history metrics data
- [ ] support related help doc
- [ ] add unit case test
