### ISSUE TITLE
[Task] <support using `Huawei Cloud SMN` send alarm notification message>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#837]
### Huawei Cloud & HertzBeat 's Feature Task 

support using `Huawei Cloud SMN` send alarm notification message, like email or discord.  
refer doc https://support.huaweicloud.com/qs-smn/smn_json.html 
api https://console.huaweicloud.com/apiexplorer/#/openapi/SMN/doc

⚠️ Please try to use rest api instead of sdk to implement this. 

### Task List

- [x] support using `Huawei Cloud SMN` send alarm notification message
- [x] support related help doc
- [ ] add unit case test
