### ISSUE TITLE
[Task] <support `EulerOS` metrics monitoring>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#838]
### Huawei Cloud & HertzBeat 's Feature Task 

support `EulerOS` metrics monitoring 
refer doc https://developer.huaweicloud.com/ict/cn/site-euleros/euleros
Please provide metrics detail document 

### Task List

- [ ] support `EulerOS` metrics monitoring 
- [ ] support related help doc
- [ ] add unit case test
