### ISSUE TITLE
[Task] <support `Huawei Cloud CCE` metrics monitoring >

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#839]
### Huawei Cloud & HertzBeat 's Feature Task 

support `Huawei Cloud CCE` metrics monitoring 
refer doc https://support.huaweicloud.com/intl/zh-cn/api-cce/cce_02_0328.html 
api doc https://console.huaweicloud.com/apiexplorer/#/openapi/CCE/doc?api=AwakeCluster 
Please provide metrics detail document 

⚠️ Please try to use k8s token to get metrics data from apiserver rest api  

### Task List

- [ ] support `Huawei Cloud CCE` metrics monitoring 
- [ ] support related help doc
- [ ] add unit case test
